const LOCATION_METADATA = Object.freeze({
	gifts: Object.freeze([
		{
			speciesId: 863,
			areaId: 73,
			areaName: 'Cerulean City Gym',
			matchAreaNames: ['Cerulean City Gym'],
			displayName: 'Cerulean City Gym (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 129,
			areaId: 22,
			areaName: 'Route 4 Poke Center',
			matchAreaNames: ['Route 4 Poke Center'],
			displayName: 'Route 4 Poke Center (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 133,
			areaId: 36,
			areaName: 'Route 5 Daycare',
			matchAreaNames: ['Route 5 Daycare'],
			displayName: 'Route 5 Daycare (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 133,
			areaId: 101,
			areaName: 'Celadon City Mansion Roof House',
			matchAreaNames: ['Celadon City Mansion Roof House'],
			displayName: 'Celadon City Mansion Roof House (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1240,
			areaId: 110,
			areaName: 'Saffron City Fighting Dojo',
			matchAreaNames: ['Saffron City Fighting Dojo'],
			displayName: 'Saffron City Fighting Dojo (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1235,
			areaId: 110,
			areaName: 'Saffron City Fighting Dojo',
			matchAreaNames: ['Saffron City Fighting Dojo'],
			displayName: 'Saffron City Fighting Dojo (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 131,
			areaId: 127,
			areaName: 'Silph Co. 7F',
			matchAreaNames: ['Silph Co. 7F'],
			displayName: 'Silph Co. 7F (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1357,
			areaId: 112,
			areaName: 'Celadon City Gym',
			matchAreaNames: ['Celadon City Gym'],
			displayName: 'Celadon City Gym (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1183,
			areaId: 177,
			areaName: 'Cerulean Cave 2F',
			matchAreaNames: ['Cerulean Cave 2F'],
			displayName: 'Cerulean Cave 2F (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1179,
			areaId: 179,
			areaName: 'Viridian City Gym',
			matchAreaNames: ['Viridian City Gym'],
			displayName: 'Viridian City Gym (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1126,
			areaId: 73,
			areaName: 'Cerulean City Gym',
			matchAreaNames: ['Cerulean City Gym'],
			displayName: 'Cerulean City Gym (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1006,
			areaId: 132,
			areaName: "Saffron City Gian's House 1F",
			matchAreaNames: ["Saffron City Gian's House 1F"],
			displayName: "Saffron City Gian's House 1F (Gift)",
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1006,
			areaId: 200,
			areaName: 'One Island Poke Center',
			matchAreaNames: ['One Island Poke Center'],
			displayName: 'One Island Poke Center (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 1088,
			areaId: 201,
			areaName: 'Treasure Beach',
			matchAreaNames: ['Treasure Beach'],
			displayName: 'Treasure Beach (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 127,
			areaId: 202,
			areaName: 'Kindle Road',
			matchAreaNames: ['Kindle Road'],
			displayName: 'Kindle Road (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 142,
			areaId: 209,
			areaName: 'Mt Ember Summit',
			matchAreaNames: ['Mt Ember Summit'],
			displayName: 'Mt Ember Summit (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 36,
			areaId: 212,
			areaName: 'Two Island House',
			matchAreaNames: ['Two Island House'],
			displayName: 'Two Island House (Gift)',
			bucket: 'fixed-gift',
		},
		{
			speciesId: 151,
			areaId: 220,
			areaName: 'Berry Forest',
			matchAreaNames: ['Berry Forest'],
			displayName: 'Berry Forest (Gift)',
			bucket: 'fixed-gift',
		},
	]),
});
